"""Lightweight metadata/source preparation only; no fitting, scoring or label preview."""
from common import *
import shutil,ast
cfg0=read(OLD/'frozen_config.json')
cfg={'task':'P2_ZERO_GOLD_CONTROLS','stage':P.name,'population':'exposed large/OBQA','actions':['R','T'],'reference':'T','families':FAMILIES,'primary_comparison':'ProbeMax versus frozen D','auxiliary_controls':['ProbeEntropy','WordD'],'gold_reference':'R2100','model':cfg0['model'],'alpha':.05,'delta':.10,'M':100,'q_grid':[j/20 for j in range(1,21)],'p_cutoff':.001,'CP_quantile':.999,'lambda':.01,'c_ref_ms':262.462515,'threshold':'inverse empirical CDF rank ceil(step*2100/20); ties included; q=1 fixed R','selection':'largest accepted q; none -> fixed Text','prefix':'The correct answer is','prefix_protocol':'original E1 generation-prefix ids + tokenizer.encode(prefix, add_special_tokens=False); no trailing space or letter; one original user and one assistant start','label_token_rule':'all non-special tokenizer vocabulary IDs whose standalone decoded string.strip() is exactly one displayed uppercase label A/B/C/D; sets nonempty/disjoint','probability':'FP32 label logsumexp then softmax conditional on union of label token sets; not P(correct)','projection':'one full receiver backbone prefill; only last valid hidden position through LM head; no cache/generate/helper','runtime':{'dtype':'bfloat16','attention':'sdpa','batch_size':1,'thinking':False,'tf32':False,'mode':'eval/inference','offline':True},'word_tfidf':read(E0/'frozen_config.json')['tfidf'],'word_LR':{'penalty':'l2','C':1,'solver':'lbfgs','max_iter':1000,'random_state':0,'class_weight':None},'fit_interface':['id','text','d'],'stage_order':['WordD fit and fit/cal scores','probe fit2100+cal1366','freeze all thresholds','read cal d and compute60','freeze all deployments','probe dev742 and WordD dev','freeze dev scores/routes','associate inherited answers/correctness for evaluation'],'bootstrap':{'seed':0,'replicates':2000,'comparisons':[f+' minus D' for f in NEW],'unit':'joint question; trained models and thresholds fixed','reference_D_means':'reuse old same-seed joint bootstrap means; old D/R2100 intervals directly cited'},'resources':{'account':'project','queue':'gpu-queue','select':1,'GPUs':1,'max_jobs':1,'walltime_seconds':1800,'GPU_allocation_hours_cap':.5,'CPU_seconds_cap':900,'preparation_reporting_CPU_reserve':120,'threads':1,'prefill_attempt_cap':4208,'fit_attempt_cap':1,'new_calibration_cap':60,'new_deployment_question_evaluations_cap':2226,'python':cfg0['resources']['python']},'new_gold':0,'new_protocol_requests':0,'helper_forwards':0,'answer_generation':0,'historical_exposure':cfg0['exposure'],'cost_identity':'new required control components plus historical complete fixed R/Text requests; not new E2E','no_probe_KV_discount':True,'old_gold_budget_closed':True,'preparation_deviation_inherited':'two historical gold rows previewed before prior subset materialization; predefined rules unchanged; Work verified all15; no deletion/resampling/rerun'}
save(P/'frozen_config.json',cfg)
sources=[]
def index(src,role):sources.append({'path':str(src),'sha256':sha(src),'bytes':src.stat().st_size,'role':role})
for n in ['fit_ids.json','cal_ids.json','dev_ids.json','group_members.csv','population_metadata.json']:
 src=OLD/'splits'/n;shutil.copyfile(src,P/'splits'/n);index(src,'inherited split/order/group')
for n in ['train_queries.jsonl','dev_queries.jsonl','candidate_fit.jsonl','candidate_cal.jsonl','TRAIN_FEATURE_INDEX.csv','DEV_FIXED_REQUEST_INDEX.csv']:
 src=OLD/'inputs'/n;shutil.copyfile(src,P/'inputs'/n);index(src,'restricted query or d interface / source index')
shutil.copyfile(OLD/'src/receiver_prompt.py',P/'src/receiver_prompt.py')
shutil.copyfile(OLD/'paper/refs_binary.bib',P/'paper/refs_binary.bib')
for src in [OLD/'frozen_config.json',OLD/'FINAL_RECEIPT.json',OLD/'models/deployment.json',OLD/'models/thresholds.json',OLD/'models/disagreement.joblib',OLD/'models/correctness_R.joblib',OLD/'src/receiver_prompt.py',OLD/'src/extract_dev.py',OLD/'src/numerics.py',OLD/'src/calibrate.py',E0/'fit_stage.py',E0/'frozen_config.json',E2E/'COST_FREEZE.json',E2E/'REQUEST_INDEX.csv',E2E/'SOURCE_INDEX.json',GOLD/'HANDOFF_ZH.md',GOLD/'P2_GOLD_BUDGET_CROSSOVER_REPORT_ZH.md']:
 index(src,'direct inherited source; no fitting or recomputation')
for d,names in [(OLD/'records',['fit_scores.jsonl','cal_scores.jsonl','dev_scored_routes.jsonl','dev_grid_routes.jsonl','dev_per_question.jsonl','dev_evaluation_labels.jsonl']),(OLD/'summary',['main_dev.csv','ranking.csv','grid_curves.csv','calibration_100.csv','paired_bootstrap.csv','bootstrap_joint_means.npz','historical_e2e_reference.csv','populations.json','computation_ledger.json'])]:
 for n in names:index(d/n,'frozen reference or post-freeze evaluation source')
for src in list((OLD/'paper').glob('1[345]*.tex'))+list((GOLD/'paper').glob('1[67]*.tex')):index(src,'integrated writing source')
csvout(P/'SOURCE_INDEX.csv',sources)
save(P/'evidence/INTERFACE_DOC_CHECK.json',{'url':'https://huggingface.co/docs/transformers/v4.52.3/chat_templating','checked_utc':utc(),'scope':'role boundaries and no duplicated special tokens; explicit user token-concatenation protocol is controlling; no framework changes'})
freeze('PROTOCOL_FREEZE.json',[P/'frozen_config.json',P/'SOURCE_INDEX.csv'],new_scores_generated=0)
freeze('SPLIT_FREEZE.json',list((P/'splits').glob('*'))+list((P/'inputs').glob('*')),no_new_split=True,no_label_preview=True)
save(P/'SESSION_RESUME_ZH.json',{'stage':'PREPARED','job_id':None,'success_ids':[],'budget_remaining':cfg['resources'],'protocol_sha256':sha(P/'PROTOCOL_FREEZE.json'),'note':'新独立授权；旧预算全部关闭；未提交；所有计算须唯一PBS作业'})
for src in (P/'src').glob('*.py'):ast.parse(src.read_text())
print(P,sha(P/'frozen_config.json'))
